FROM public.ecr.aws/lambda/python:3.11

WORKDIR /

COPY ./transcriber/whisper.py ./
COPY ./transcriber/requirements.txt ./

RUN pip3 install -r requirements.txt —target "${LAMBDA_TASK_ROOT}"

CMD [ "app.handler" ]